#!/bin/sh
set -e  # Exit immediately if any command exits with a non-zero status

echo ""
echo '* Verify dependencies'
go mod verify

echo ""
echo '* Run: go-modernize'
modernize -test ./...

echo ""
echo '* Run: golangci'
golangci-lint run ./...

echo ""
echo '* Run: all tests and generate coverage report'
go clean -testcache
go test -count=1 -timeout 30s $(go list ./... | grep -Ev 'examples|components') -covermode=atomic