// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.598
package goaster

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"
import "strings"

func GoasterCSS() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templ.WriteWatchModeString(templ_7745c5c3_Buffer, 1)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}

func gttContainer() templ.CSSClass {
	var templ_7745c5c3_CSSBuilder strings.Builder
	templ_7745c5c3_CSSBuilder.WriteString(`position:fixed;`)
	templ_7745c5c3_CSSBuilder.WriteString(`z-index:1000;`)
	templ_7745c5c3_CSSBuilder.WriteString(`display:flex;`)
	templ_7745c5c3_CSSBuilder.WriteString(`flex-direction:column-reverse;`)
	templ_7745c5c3_CSSBuilder.WriteString(`align-items:flex-end;`)
	templ_7745c5c3_CSSBuilder.WriteString(`max-height:90%;`)
	templ_7745c5c3_CSSBuilder.WriteString(`overflow-y:auto;`)
	templ_7745c5c3_CSSBuilder.WriteString(`font-family:var(--gtt-font-family);`)
	templ_7745c5c3_CSSBuilder.WriteString(`font-size:var(--gtt-font-size);`)
	templ_7745c5c3_CSSBuilder.WriteString(`line-height:var(--gtt-line-height);`)
	templ_7745c5c3_CSSID := templ.CSSID(`gttContainer`, templ_7745c5c3_CSSBuilder.String())
	return templ.ComponentCSSClass{
		ID:    templ_7745c5c3_CSSID,
		Class: templ.SafeCSS(`.` + templ_7745c5c3_CSSID + `{` + templ_7745c5c3_CSSBuilder.String() + `}`),
	}
}

func gttContainerBottomRight() templ.CSSClass {
	var templ_7745c5c3_CSSBuilder strings.Builder
	templ_7745c5c3_CSSBuilder.WriteString(`right:15px;`)
	templ_7745c5c3_CSSBuilder.WriteString(`bottom:15px;`)
	templ_7745c5c3_CSSBuilder.WriteString(`align-items:flex-end;`)
	templ_7745c5c3_CSSID := templ.CSSID(`gttContainerBottomRight`, templ_7745c5c3_CSSBuilder.String())
	return templ.ComponentCSSClass{
		ID:    templ_7745c5c3_CSSID,
		Class: templ.SafeCSS(`.` + templ_7745c5c3_CSSID + `{` + templ_7745c5c3_CSSBuilder.String() + `}`),
	}
}

func gttContainerBottomLeft() templ.CSSClass {
	var templ_7745c5c3_CSSBuilder strings.Builder
	templ_7745c5c3_CSSBuilder.WriteString(`left:15px;`)
	templ_7745c5c3_CSSBuilder.WriteString(`bottom:15px;`)
	templ_7745c5c3_CSSBuilder.WriteString(`align-items:flex-start;`)
	templ_7745c5c3_CSSID := templ.CSSID(`gttContainerBottomLeft`, templ_7745c5c3_CSSBuilder.String())
	return templ.ComponentCSSClass{
		ID:    templ_7745c5c3_CSSID,
		Class: templ.SafeCSS(`.` + templ_7745c5c3_CSSID + `{` + templ_7745c5c3_CSSBuilder.String() + `}`),
	}
}

func gttContainerBottomCenter() templ.CSSClass {
	var templ_7745c5c3_CSSBuilder strings.Builder
	templ_7745c5c3_CSSBuilder.WriteString(`left:50%;`)
	templ_7745c5c3_CSSBuilder.WriteString(`bottom:15px;`)
	templ_7745c5c3_CSSBuilder.WriteString(`transform:translateX(-50%);`)
	templ_7745c5c3_CSSBuilder.WriteString(`align-items:center;`)
	templ_7745c5c3_CSSID := templ.CSSID(`gttContainerBottomCenter`, templ_7745c5c3_CSSBuilder.String())
	return templ.ComponentCSSClass{
		ID:    templ_7745c5c3_CSSID,
		Class: templ.SafeCSS(`.` + templ_7745c5c3_CSSID + `{` + templ_7745c5c3_CSSBuilder.String() + `}`),
	}
}

func gttContainerTopRight() templ.CSSClass {
	var templ_7745c5c3_CSSBuilder strings.Builder
	templ_7745c5c3_CSSBuilder.WriteString(`right:15px;`)
	templ_7745c5c3_CSSBuilder.WriteString(`top:15px;`)
	templ_7745c5c3_CSSBuilder.WriteString(`align-items:flex-end;`)
	templ_7745c5c3_CSSID := templ.CSSID(`gttContainerTopRight`, templ_7745c5c3_CSSBuilder.String())
	return templ.ComponentCSSClass{
		ID:    templ_7745c5c3_CSSID,
		Class: templ.SafeCSS(`.` + templ_7745c5c3_CSSID + `{` + templ_7745c5c3_CSSBuilder.String() + `}`),
	}
}

func gttContainerTopLeft() templ.CSSClass {
	var templ_7745c5c3_CSSBuilder strings.Builder
	templ_7745c5c3_CSSBuilder.WriteString(`left:15px;`)
	templ_7745c5c3_CSSBuilder.WriteString(`top:15px;`)
	templ_7745c5c3_CSSBuilder.WriteString(`align-items:flex-start;`)
	templ_7745c5c3_CSSID := templ.CSSID(`gttContainerTopLeft`, templ_7745c5c3_CSSBuilder.String())
	return templ.ComponentCSSClass{
		ID:    templ_7745c5c3_CSSID,
		Class: templ.SafeCSS(`.` + templ_7745c5c3_CSSID + `{` + templ_7745c5c3_CSSBuilder.String() + `}`),
	}
}

func gttContainerTopCenter() templ.CSSClass {
	var templ_7745c5c3_CSSBuilder strings.Builder
	templ_7745c5c3_CSSBuilder.WriteString(`left:50%;`)
	templ_7745c5c3_CSSBuilder.WriteString(`top:15px;`)
	templ_7745c5c3_CSSBuilder.WriteString(`transform:translateX(-50%);`)
	templ_7745c5c3_CSSBuilder.WriteString(`align-items:center;`)
	templ_7745c5c3_CSSID := templ.CSSID(`gttContainerTopCenter`, templ_7745c5c3_CSSBuilder.String())
	return templ.ComponentCSSClass{
		ID:    templ_7745c5c3_CSSID,
		Class: templ.SafeCSS(`.` + templ_7745c5c3_CSSID + `{` + templ_7745c5c3_CSSBuilder.String() + `}`),
	}
}

func gttToast() templ.CSSClass {
	var templ_7745c5c3_CSSBuilder strings.Builder
	templ_7745c5c3_CSSBuilder.WriteString(`position:relative;`)
	templ_7745c5c3_CSSBuilder.WriteString(`min-width:250px;`)
	templ_7745c5c3_CSSBuilder.WriteString(`margin-top:0.5rem;`)
	templ_7745c5c3_CSSBuilder.WriteString(`background-color:var(--gtt-bg);`)
	templ_7745c5c3_CSSBuilder.WriteString(`color:var(--gtt-color);`)
	templ_7745c5c3_CSSBuilder.WriteString(`border-radius:var(--gtt-border-radius);`)
	templ_7745c5c3_CSSBuilder.WriteString(`border-color:var(--gtt-border-color);`)
	templ_7745c5c3_CSSBuilder.WriteString(`padding:var(--gtt-py) var(--gtt-px);`)
	templ_7745c5c3_CSSBuilder.WriteString(`display:flex;`)
	templ_7745c5c3_CSSBuilder.WriteString(`align-items:center;`)
	templ_7745c5c3_CSSBuilder.WriteString(`justify-content:space-between;`)
	templ_7745c5c3_CSSID := templ.CSSID(`gttToast`, templ_7745c5c3_CSSBuilder.String())
	return templ.ComponentCSSClass{
		ID:    templ_7745c5c3_CSSID,
		Class: templ.SafeCSS(`.` + templ_7745c5c3_CSSID + `{` + templ_7745c5c3_CSSBuilder.String() + `}`),
	}
}

func gttAccent() templ.CSSClass {
	var templ_7745c5c3_CSSBuilder strings.Builder
	templ_7745c5c3_CSSBuilder.WriteString(`--gtt-border-radius:0;`)
	templ_7745c5c3_CSSBuilder.WriteString(`border:0;`)
	templ_7745c5c3_CSSBuilder.WriteString(`border-left-width:4px;`)
	templ_7745c5c3_CSSBuilder.WriteString(`border-left-style:solid;`)
	templ_7745c5c3_CSSID := templ.CSSID(`gttAccent`, templ_7745c5c3_CSSBuilder.String())
	return templ.ComponentCSSClass{
		ID:    templ_7745c5c3_CSSID,
		Class: templ.SafeCSS(`.` + templ_7745c5c3_CSSID + `{` + templ_7745c5c3_CSSBuilder.String() + `}`),
	}
}

func gttBordered() templ.CSSClass {
	var templ_7745c5c3_CSSBuilder strings.Builder
	templ_7745c5c3_CSSBuilder.WriteString(`border-style:var(--gtt-border-style);`)
	templ_7745c5c3_CSSBuilder.WriteString(`border-width:var(--gtt-border-width);`)
	templ_7745c5c3_CSSID := templ.CSSID(`gttBordered`, templ_7745c5c3_CSSBuilder.String())
	return templ.ComponentCSSClass{
		ID:    templ_7745c5c3_CSSID,
		Class: templ.SafeCSS(`.` + templ_7745c5c3_CSSID + `{` + templ_7745c5c3_CSSBuilder.String() + `}`),
	}
}

func gttAnimated() templ.CSSClass {
	var templ_7745c5c3_CSSBuilder strings.Builder
	templ_7745c5c3_CSSBuilder.WriteString(`animation-duration:var(--gtt-animation-entrance-duration);`)
	templ_7745c5c3_CSSBuilder.WriteString(`animation-direction:var(--gtt-animation-entrance-direction);`)
	templ_7745c5c3_CSSBuilder.WriteString(`animation-timing-function:var(--gtt-animation-entrance-timing-function);`)
	templ_7745c5c3_CSSBuilder.WriteString(`animation-delay:var(--gtt-animation-entrance-delay);`)
	templ_7745c5c3_CSSID := templ.CSSID(`gttAnimated`, templ_7745c5c3_CSSBuilder.String())
	return templ.ComponentCSSClass{
		ID:    templ_7745c5c3_CSSID,
		Class: templ.SafeCSS(`.` + templ_7745c5c3_CSSID + `{` + templ_7745c5c3_CSSBuilder.String() + `}`),
	}
}

func gttShow() templ.CSSClass {
	var templ_7745c5c3_CSSBuilder strings.Builder
	templ_7745c5c3_CSSBuilder.WriteString(`visibility:visible;`)
	templ_7745c5c3_CSSID := templ.CSSID(`gttShow`, templ_7745c5c3_CSSBuilder.String())
	return templ.ComponentCSSClass{
		ID:    templ_7745c5c3_CSSID,
		Class: templ.SafeCSS(`.` + templ_7745c5c3_CSSID + `{` + templ_7745c5c3_CSSBuilder.String() + `}`),
	}
}

func gttShowFromTop() templ.CSSClass {
	var templ_7745c5c3_CSSBuilder strings.Builder
	templ_7745c5c3_CSSBuilder.WriteString(`animation-name:var(--gtt-animation-entrance-name-top);`)
	templ_7745c5c3_CSSID := templ.CSSID(`gttShowFromTop`, templ_7745c5c3_CSSBuilder.String())
	return templ.ComponentCSSClass{
		ID:    templ_7745c5c3_CSSID,
		Class: templ.SafeCSS(`.` + templ_7745c5c3_CSSID + `{` + templ_7745c5c3_CSSBuilder.String() + `}`),
	}
}

func gttShowFromBottom() templ.CSSClass {
	var templ_7745c5c3_CSSBuilder strings.Builder
	templ_7745c5c3_CSSBuilder.WriteString(`animation-name:var(--gtt-animation-entrance-name-bottom);`)
	templ_7745c5c3_CSSID := templ.CSSID(`gttShowFromBottom`, templ_7745c5c3_CSSBuilder.String())
	return templ.ComponentCSSClass{
		ID:    templ_7745c5c3_CSSID,
		Class: templ.SafeCSS(`.` + templ_7745c5c3_CSSID + `{` + templ_7745c5c3_CSSBuilder.String() + `}`),
	}
}

func gttProgressBar() templ.CSSClass {
	var templ_7745c5c3_CSSBuilder strings.Builder
	templ_7745c5c3_CSSBuilder.WriteString(`position:absolute;`)
	templ_7745c5c3_CSSBuilder.WriteString(`overflow:hidden;`)
	templ_7745c5c3_CSSBuilder.WriteString(`top:0;`)
	templ_7745c5c3_CSSBuilder.WriteString(`left:0;`)
	templ_7745c5c3_CSSBuilder.WriteString(`height:4px;`)
	templ_7745c5c3_CSSBuilder.WriteString(`background-color:var(--gtt-progress-bar-color);`)
	templ_7745c5c3_CSSBuilder.WriteString(`width:100%;`)
	templ_7745c5c3_CSSBuilder.WriteString(`transition:width linear;`)
	templ_7745c5c3_CSSID := templ.CSSID(`gttProgressBar`, templ_7745c5c3_CSSBuilder.String())
	return templ.ComponentCSSClass{
		ID:    templ_7745c5c3_CSSID,
		Class: templ.SafeCSS(`.` + templ_7745c5c3_CSSID + `{` + templ_7745c5c3_CSSBuilder.String() + `}`),
	}
}

func gttDefaultLevel() templ.CSSClass {
	var templ_7745c5c3_CSSBuilder strings.Builder
	templ_7745c5c3_CSSBuilder.WriteString(`--gtt-color:var(--gtt-default-color);`)
	templ_7745c5c3_CSSBuilder.WriteString(`--gtt-bg:var(--gtt-default-bg);`)
	templ_7745c5c3_CSSBuilder.WriteString(`--gtt-border-color:var(--gtt-default-border-color);`)
	templ_7745c5c3_CSSBuilder.WriteString(`--gtt-progress-bar-color:var(--gtt-default-progress-bar-color);`)
	templ_7745c5c3_CSSID := templ.CSSID(`gttDefaultLevel`, templ_7745c5c3_CSSBuilder.String())
	return templ.ComponentCSSClass{
		ID:    templ_7745c5c3_CSSID,
		Class: templ.SafeCSS(`.` + templ_7745c5c3_CSSID + `{` + templ_7745c5c3_CSSBuilder.String() + `}`),
	}
}

func gttAccentLightDefaultLevel() templ.CSSClass {
	var templ_7745c5c3_CSSBuilder strings.Builder
	templ_7745c5c3_CSSBuilder.WriteString(`--gtt-color:var(--gtt-default-accent-color);`)
	templ_7745c5c3_CSSBuilder.WriteString(`--gtt-bg:var(--gtt-accent-light-bg);`)
	templ_7745c5c3_CSSBuilder.WriteString(`--gtt-border-color:var(--gtt-default-border-color);`)
	templ_7745c5c3_CSSBuilder.WriteString(`border-left-color:var(--gtt-default-accent-border-color, #6b7280);`)
	templ_7745c5c3_CSSID := templ.CSSID(`gttAccentLightDefaultLevel`, templ_7745c5c3_CSSBuilder.String())
	return templ.ComponentCSSClass{
		ID:    templ_7745c5c3_CSSID,
		Class: templ.SafeCSS(`.` + templ_7745c5c3_CSSID + `{` + templ_7745c5c3_CSSBuilder.String() + `}`),
	}
}

func gttAccentDarkDefaultLevel() templ.CSSClass {
	var templ_7745c5c3_CSSBuilder strings.Builder
	templ_7745c5c3_CSSBuilder.WriteString(`--gtt-color:var(--gtt-default-accent-dark-color);`)
	templ_7745c5c3_CSSBuilder.WriteString(`--gtt-bg:var(--gtt-accent-dark-bg);`)
	templ_7745c5c3_CSSBuilder.WriteString(`--gtt-border-color:var(--gtt-default-border-color);`)
	templ_7745c5c3_CSSBuilder.WriteString(`border-left-color:var(--gtt-success-accent-border-color, #6b7280);`)
	templ_7745c5c3_CSSID := templ.CSSID(`gttAccentDarkDefaultLevel`, templ_7745c5c3_CSSBuilder.String())
	return templ.ComponentCSSClass{
		ID:    templ_7745c5c3_CSSID,
		Class: templ.SafeCSS(`.` + templ_7745c5c3_CSSID + `{` + templ_7745c5c3_CSSBuilder.String() + `}`),
	}
}

func gttSuccessLevel() templ.CSSClass {
	var templ_7745c5c3_CSSBuilder strings.Builder
	templ_7745c5c3_CSSBuilder.WriteString(`--gtt-color:var(--gtt-success-color);`)
	templ_7745c5c3_CSSBuilder.WriteString(`--gtt-bg:var(--gtt-success-bg);`)
	templ_7745c5c3_CSSBuilder.WriteString(`--gtt-border-color:var(--gtt-success-border-color);`)
	templ_7745c5c3_CSSBuilder.WriteString(`--gtt-progress-bar-color:var(--gtt-success-progress-bar-color);`)
	templ_7745c5c3_CSSID := templ.CSSID(`gttSuccessLevel`, templ_7745c5c3_CSSBuilder.String())
	return templ.ComponentCSSClass{
		ID:    templ_7745c5c3_CSSID,
		Class: templ.SafeCSS(`.` + templ_7745c5c3_CSSID + `{` + templ_7745c5c3_CSSBuilder.String() + `}`),
	}
}

func gttAccentLightSuccessLevel() templ.CSSClass {
	var templ_7745c5c3_CSSBuilder strings.Builder
	templ_7745c5c3_CSSBuilder.WriteString(`--gtt-color:var(--gtt-success-accent-color);`)
	templ_7745c5c3_CSSBuilder.WriteString(`--gtt-bg:var(--gtt-accent-light-bg);`)
	templ_7745c5c3_CSSBuilder.WriteString(`--gtt-border-color:var(--gtt-success-border-color);`)
	templ_7745c5c3_CSSBuilder.WriteString(`border-left-color:var(--gtt-success-accent-dark-color, #22c55e);`)
	templ_7745c5c3_CSSID := templ.CSSID(`gttAccentLightSuccessLevel`, templ_7745c5c3_CSSBuilder.String())
	return templ.ComponentCSSClass{
		ID:    templ_7745c5c3_CSSID,
		Class: templ.SafeCSS(`.` + templ_7745c5c3_CSSID + `{` + templ_7745c5c3_CSSBuilder.String() + `}`),
	}
}

func gttAccentDarkSuccessLevel() templ.CSSClass {
	var templ_7745c5c3_CSSBuilder strings.Builder
	templ_7745c5c3_CSSBuilder.WriteString(`--gtt-color:var(--gtt-success-accent-dark-color);`)
	templ_7745c5c3_CSSBuilder.WriteString(`--gtt-bg:var(--gtt-accent-dark-bg);`)
	templ_7745c5c3_CSSBuilder.WriteString(`--gtt-border-color:var(--gtt-success-border-color);`)
	templ_7745c5c3_CSSBuilder.WriteString(`border-left-color:var(--gtt-success-accent-border-color, #22c55e);`)
	templ_7745c5c3_CSSID := templ.CSSID(`gttAccentDarkSuccessLevel`, templ_7745c5c3_CSSBuilder.String())
	return templ.ComponentCSSClass{
		ID:    templ_7745c5c3_CSSID,
		Class: templ.SafeCSS(`.` + templ_7745c5c3_CSSID + `{` + templ_7745c5c3_CSSBuilder.String() + `}`),
	}
}

func gttErrorLevel() templ.CSSClass {
	var templ_7745c5c3_CSSBuilder strings.Builder
	templ_7745c5c3_CSSBuilder.WriteString(`--gtt-color:var(--gtt-error-color);`)
	templ_7745c5c3_CSSBuilder.WriteString(`--gtt-bg:var(--gtt-error-bg);`)
	templ_7745c5c3_CSSBuilder.WriteString(`--gtt-border-color:var(--gtt-error-border-color);`)
	templ_7745c5c3_CSSBuilder.WriteString(`--gtt-progress-bar-color:var(--gtt-error-progress-bar-color);`)
	templ_7745c5c3_CSSID := templ.CSSID(`gttErrorLevel`, templ_7745c5c3_CSSBuilder.String())
	return templ.ComponentCSSClass{
		ID:    templ_7745c5c3_CSSID,
		Class: templ.SafeCSS(`.` + templ_7745c5c3_CSSID + `{` + templ_7745c5c3_CSSBuilder.String() + `}`),
	}
}

func gttAccentLightErrorLevel() templ.CSSClass {
	var templ_7745c5c3_CSSBuilder strings.Builder
	templ_7745c5c3_CSSBuilder.WriteString(`--gtt-color:var(--gtt-error-accent-color);`)
	templ_7745c5c3_CSSBuilder.WriteString(`--gtt-bg:var(--gtt-accent-light-bg);`)
	templ_7745c5c3_CSSBuilder.WriteString(`--gtt-border-color:var(--gtt-error-border-color);`)
	templ_7745c5c3_CSSBuilder.WriteString(`border-left-color:var(--gtt-error-accent-border-color, #ef4444);`)
	templ_7745c5c3_CSSID := templ.CSSID(`gttAccentLightErrorLevel`, templ_7745c5c3_CSSBuilder.String())
	return templ.ComponentCSSClass{
		ID:    templ_7745c5c3_CSSID,
		Class: templ.SafeCSS(`.` + templ_7745c5c3_CSSID + `{` + templ_7745c5c3_CSSBuilder.String() + `}`),
	}
}

func gttAccentDarkErrorLevel() templ.CSSClass {
	var templ_7745c5c3_CSSBuilder strings.Builder
	templ_7745c5c3_CSSBuilder.WriteString(`--gtt-color:var(--gtt-error-accent-dark-color);`)
	templ_7745c5c3_CSSBuilder.WriteString(`--gtt-bg:var(--gtt-accent-dark-bg);`)
	templ_7745c5c3_CSSBuilder.WriteString(`--gtt-border-color:var(--gtt-error-border-color);`)
	templ_7745c5c3_CSSBuilder.WriteString(`border-left-color:var(--gtt-error-accent-border-color, #ef4444);`)
	templ_7745c5c3_CSSID := templ.CSSID(`gttAccentDarkErrorLevel`, templ_7745c5c3_CSSBuilder.String())
	return templ.ComponentCSSClass{
		ID:    templ_7745c5c3_CSSID,
		Class: templ.SafeCSS(`.` + templ_7745c5c3_CSSID + `{` + templ_7745c5c3_CSSBuilder.String() + `}`),
	}
}

func gttWarningLevel() templ.CSSClass {
	var templ_7745c5c3_CSSBuilder strings.Builder
	templ_7745c5c3_CSSBuilder.WriteString(`--gtt-color:var(--gtt-warning-color);`)
	templ_7745c5c3_CSSBuilder.WriteString(`--gtt-bg:var(--gtt-warning-bg);`)
	templ_7745c5c3_CSSBuilder.WriteString(`--gtt-border-color:var(--gtt-warning-border-color);`)
	templ_7745c5c3_CSSBuilder.WriteString(`--gtt-progress-bar-color:var(--gtt-warning-progress-bar-color);`)
	templ_7745c5c3_CSSID := templ.CSSID(`gttWarningLevel`, templ_7745c5c3_CSSBuilder.String())
	return templ.ComponentCSSClass{
		ID:    templ_7745c5c3_CSSID,
		Class: templ.SafeCSS(`.` + templ_7745c5c3_CSSID + `{` + templ_7745c5c3_CSSBuilder.String() + `}`),
	}
}

func gttAccentLightWarningLevel() templ.CSSClass {
	var templ_7745c5c3_CSSBuilder strings.Builder
	templ_7745c5c3_CSSBuilder.WriteString(`--gtt-color:var(--gtt-warning-accent-color);`)
	templ_7745c5c3_CSSBuilder.WriteString(`--gtt-bg:var(--gtt-accent-light-bg);`)
	templ_7745c5c3_CSSBuilder.WriteString(`--gtt-border-color:var(--gtt-warning-border-color);`)
	templ_7745c5c3_CSSBuilder.WriteString(`border-left-color:var(--gtt-warning-accent-border-color, #f97316);`)
	templ_7745c5c3_CSSID := templ.CSSID(`gttAccentLightWarningLevel`, templ_7745c5c3_CSSBuilder.String())
	return templ.ComponentCSSClass{
		ID:    templ_7745c5c3_CSSID,
		Class: templ.SafeCSS(`.` + templ_7745c5c3_CSSID + `{` + templ_7745c5c3_CSSBuilder.String() + `}`),
	}
}

func gttAccentDarkWarningLevel() templ.CSSClass {
	var templ_7745c5c3_CSSBuilder strings.Builder
	templ_7745c5c3_CSSBuilder.WriteString(`--gtt-color:var(--gtt-warning-accent-dark-color);`)
	templ_7745c5c3_CSSBuilder.WriteString(`--gtt-bg:var(--gtt-accent-dark-bg);`)
	templ_7745c5c3_CSSBuilder.WriteString(`--gtt-border-color:var(--gtt-warning-border-color);`)
	templ_7745c5c3_CSSBuilder.WriteString(`border-left-color:var(--gtt-warning-accent-border-color, #f97316);`)
	templ_7745c5c3_CSSID := templ.CSSID(`gttAccentDarkWarningLevel`, templ_7745c5c3_CSSBuilder.String())
	return templ.ComponentCSSClass{
		ID:    templ_7745c5c3_CSSID,
		Class: templ.SafeCSS(`.` + templ_7745c5c3_CSSID + `{` + templ_7745c5c3_CSSBuilder.String() + `}`),
	}
}

func gttInfoLevel() templ.CSSClass {
	var templ_7745c5c3_CSSBuilder strings.Builder
	templ_7745c5c3_CSSBuilder.WriteString(`--gtt-color:var(--gtt-info-color);`)
	templ_7745c5c3_CSSBuilder.WriteString(`--gtt-bg:var(--gtt-info-bg);`)
	templ_7745c5c3_CSSBuilder.WriteString(`--gtt-border-color:var(--gtt-info-border-color);`)
	templ_7745c5c3_CSSBuilder.WriteString(`--gtt-progress-bar-color:var(--gtt-info-progress-bar-color);`)
	templ_7745c5c3_CSSID := templ.CSSID(`gttInfoLevel`, templ_7745c5c3_CSSBuilder.String())
	return templ.ComponentCSSClass{
		ID:    templ_7745c5c3_CSSID,
		Class: templ.SafeCSS(`.` + templ_7745c5c3_CSSID + `{` + templ_7745c5c3_CSSBuilder.String() + `}`),
	}
}

func gttAccentLightInfoLevel() templ.CSSClass {
	var templ_7745c5c3_CSSBuilder strings.Builder
	templ_7745c5c3_CSSBuilder.WriteString(`--gtt-color:var(--gtt-info-accent-color);`)
	templ_7745c5c3_CSSBuilder.WriteString(`--gtt-bg:var(--gtt-accent-light-bg);`)
	templ_7745c5c3_CSSBuilder.WriteString(`--gtt-border-color:var(--gtt-info-border-color);`)
	templ_7745c5c3_CSSBuilder.WriteString(`border-left-color:var(--gtt-info-accent-border-color, #3b82f6);`)
	templ_7745c5c3_CSSID := templ.CSSID(`gttAccentLightInfoLevel`, templ_7745c5c3_CSSBuilder.String())
	return templ.ComponentCSSClass{
		ID:    templ_7745c5c3_CSSID,
		Class: templ.SafeCSS(`.` + templ_7745c5c3_CSSID + `{` + templ_7745c5c3_CSSBuilder.String() + `}`),
	}
}

func gttAccentDarkInfoLevel() templ.CSSClass {
	var templ_7745c5c3_CSSBuilder strings.Builder
	templ_7745c5c3_CSSBuilder.WriteString(`--gtt-color:var(--gtt-info-accent-dark-color);`)
	templ_7745c5c3_CSSBuilder.WriteString(`--gtt-bg:var(--gtt-accent-dark-bg);`)
	templ_7745c5c3_CSSBuilder.WriteString(`--gtt-border-color:var(--gtt-info-border-color);`)
	templ_7745c5c3_CSSBuilder.WriteString(`border-left-color:var(--gtt-info-accent-border-color, #3b82f6);`)
	templ_7745c5c3_CSSID := templ.CSSID(`gttAccentDarkInfoLevel`, templ_7745c5c3_CSSBuilder.String())
	return templ.ComponentCSSClass{
		ID:    templ_7745c5c3_CSSID,
		Class: templ.SafeCSS(`.` + templ_7745c5c3_CSSID + `{` + templ_7745c5c3_CSSBuilder.String() + `}`),
	}
}

func gttIcon() templ.CSSClass {
	var templ_7745c5c3_CSSBuilder strings.Builder
	templ_7745c5c3_CSSBuilder.WriteString(`display:inline-flex;`)
	templ_7745c5c3_CSSBuilder.WriteString(`align-items:center;`)
	templ_7745c5c3_CSSBuilder.WriteString(`flex-shrink:0;`)
	templ_7745c5c3_CSSBuilder.WriteString(`width:1.125rem;`)
	templ_7745c5c3_CSSBuilder.WriteString(`height:1.125rem;`)
	templ_7745c5c3_CSSID := templ.CSSID(`gttIcon`, templ_7745c5c3_CSSBuilder.String())
	return templ.ComponentCSSClass{
		ID:    templ_7745c5c3_CSSID,
		Class: templ.SafeCSS(`.` + templ_7745c5c3_CSSID + `{` + templ_7745c5c3_CSSBuilder.String() + `}`),
	}
}

func gttMessage() templ.CSSClass {
	var templ_7745c5c3_CSSBuilder strings.Builder
	templ_7745c5c3_CSSBuilder.WriteString(`margin:1em 0 1em 0.75em;`)
	templ_7745c5c3_CSSID := templ.CSSID(`gttMessage`, templ_7745c5c3_CSSBuilder.String())
	return templ.ComponentCSSClass{
		ID:    templ_7745c5c3_CSSID,
		Class: templ.SafeCSS(`.` + templ_7745c5c3_CSSID + `{` + templ_7745c5c3_CSSBuilder.String() + `}`),
	}
}

func gttCloseBtn() templ.CSSClass {
	var templ_7745c5c3_CSSBuilder strings.Builder
	templ_7745c5c3_CSSBuilder.WriteString(`margin-left:auto;`)
	templ_7745c5c3_CSSBuilder.WriteString(`display:inline-flex;`)
	templ_7745c5c3_CSSBuilder.WriteString(`align-items:center;`)
	templ_7745c5c3_CSSBuilder.WriteString(`background-color:transparent;`)
	templ_7745c5c3_CSSBuilder.WriteString(`border:none;`)
	templ_7745c5c3_CSSBuilder.WriteString(`border-radius:1e5px;`)
	templ_7745c5c3_CSSBuilder.WriteString(`aspect-ratio:1;`)
	templ_7745c5c3_CSSBuilder.WriteString(`color:inherit;`)
	templ_7745c5c3_CSSBuilder.WriteString(`cursor:pointer;`)
	templ_7745c5c3_CSSBuilder.WriteString(`transition:background 0.3s cubic-bezier(0.4, 0, 0.2, 1);`)
	templ_7745c5c3_CSSID := templ.CSSID(`gttCloseBtn`, templ_7745c5c3_CSSBuilder.String())
	return templ.ComponentCSSClass{
		ID:    templ_7745c5c3_CSSID,
		Class: templ.SafeCSS(`.` + templ_7745c5c3_CSSID + `{` + templ_7745c5c3_CSSBuilder.String() + `}`),
	}
}

func gttSrOnly() templ.CSSClass {
	var templ_7745c5c3_CSSBuilder strings.Builder
	templ_7745c5c3_CSSBuilder.WriteString(`position:absolute;`)
	templ_7745c5c3_CSSBuilder.WriteString(`width:1px;`)
	templ_7745c5c3_CSSBuilder.WriteString(`height:1px;`)
	templ_7745c5c3_CSSBuilder.WriteString(`padding:0;`)
	templ_7745c5c3_CSSBuilder.WriteString(`margin:-1px;`)
	templ_7745c5c3_CSSBuilder.WriteString(`overflow:hidden;`)
	templ_7745c5c3_CSSBuilder.WriteString(`clip:rect(0, 0, 0, 0);`)
	templ_7745c5c3_CSSBuilder.WriteString(`white-space:nowrap;`)
	templ_7745c5c3_CSSBuilder.WriteString(`border-width:0;`)
	templ_7745c5c3_CSSID := templ.CSSID(`gttSrOnly`, templ_7745c5c3_CSSBuilder.String())
	return templ.ComponentCSSClass{
		ID:    templ_7745c5c3_CSSID,
		Class: templ.SafeCSS(`.` + templ_7745c5c3_CSSID + `{` + templ_7745c5c3_CSSBuilder.String() + `}`),
	}
}
