// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.960
package variants

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func variantMinimal() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		toasterMinimalVariantHandle := templ.NewOnceHandle()
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<style type=\"text/css\" nonce=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var3 string
			templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(templ.GetNonce(ctx))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `components/css/variants/minimal.templ`, Line: 6, Col: 52}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "\">\n/* [tempo] BEGIN - Do not edit! This section is auto-generated. */\n:root{--gtt-minimal-default-color: var(--gtt-color-default-dark);--gtt-minimal-success-color: var(--gtt-color-success-dark);--gtt-minimal-error-color: var(--gtt-color-error-dark);--gtt-minimal-warning-color: var(--gtt-color-warning-dark);--gtt-minimal-info-color: var(--gtt-color-info-dark)}@media (prefers-color-scheme: dark){:root{--gtt-minimal-default-color: var(--gtt-color-default-light);--gtt-minimal-success-color: var(--gtt-color-success-light);--gtt-minimal-error-color: var(--gtt-color-error-light);--gtt-minimal-warning-color: var(--gtt-color-warning-light);--gtt-minimal-info-color: var(--gtt-color-info-light)}}.gttToast[role=alert][data-variant=minimal]{border:0;box-shadow:none}.gttToast[role=alert][data-level=default][data-variant=minimal]{--_gtt-color: var(--gtt-minimal-default-color);--_gtt-bg: transparent;--_gtt-border-color: transparent;--_gtt-progress-color: var(--gtt-minimal-default-color)}.gttToast[role=alert][data-level=success][data-variant=minimal]{--_gtt-color: var(--gtt-minimal-success-color);--_gtt-bg: transparent;--_gtt-border-color: transparent;--_gtt-progress-color: var(--gtt-minimal-success-color)}.gttToast[role=alert][data-level=error][data-variant=minimal]{--_gtt-color: var(--gtt-minimal-error-color);--_gtt-bg: transparent;--_gtt-border-color: transparent;--_gtt-progress-color: var(--gtt-minimal-error-color)}.gttToast[role=alert][data-level=warning][data-variant=minimal]{--_gtt-color: var(--gtt-minimal-warning-color);--_gtt-bg: transparent;--_gtt-border-color: transparent;--_gtt-progress-color: var(--gtt-minimal-warning-color)}.gttToast[role=alert][data-level=info][data-variant=minimal]{--_gtt-color: var(--gtt-minimal-info-color);--_gtt-bg: transparent;--_gtt-border-color: transparent;--_gtt-progress-color: var(--gtt-minimal-info-color)}\n\n/* [tempo] END */\n</style>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = toasterMinimalVariantHandle.Once().Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
