// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.943
package styles

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

var navigationCSSHandle = templ.NewOnceHandle()

func Navigation() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<style type=\"text/css\" nonce=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var3 string
			templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(templ.GetNonce(ctx))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `examples/styles/nav.templ`, Line: 7, Col: 52}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "\">\n@layer base {\n  .nav {\n    list-style: none;\n    padding: 1rem;\n    margin: 0;\n    background-color: var(--bg-color);\n    border: 1px solid rgba(0, 0, 0, 0.1);\n    border-radius: 0.5rem;\n    max-width: 320px;\n    font-family: inherit;\n    box-shadow: 0 2px 6px rgba(0, 0, 0, 0.05);\n  }\n\n  .nav li {\n    margin: 0.25rem 0;\n    }\n\n    .nav a {\n    display: block;\n    padding: 0.5rem 0.75rem;\n    color: var(--text-color);\n    text-decoration: none;\n    border-radius: 0.375rem;\n    transition: background-color 0.2s ease, color 0.2s ease;\n    }\n\n    .nav a:hover {\n    background-color: rgba(0, 0, 0, 0.05);\n    }\n\n    .nav-sub {\n    list-style: none;\n    padding-left: 1rem;\n    margin-top: 0.25rem;\n    }\n\n    .nav-sub a {\n    font-size: 0.9rem;\n    color: var(--text-color);\n    opacity: 0.8;\n    }\n\n    .nav-sub a:hover {\n    background-color: rgba(0, 0, 0, 0.08);\n    opacity: 1;\n    }\n\n    @media (prefers-color-scheme: dark) {\n    .nav {\n        border-color: rgba(255, 255, 255, 0.1);\n        box-shadow: 0 2px 6px rgba(0, 0, 0, 0.2);\n    }\n\n    .nav a:hover {\n        background-color: rgba(255, 255, 255, 0.1);\n    }\n\n    .nav-sub a:hover {\n        background-color: rgba(255, 255, 255, 0.15);\n    }\n    }\n}\n</style>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = navigationCSSHandle.Once().Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
